-- NoxSoft Database Initialization
-- Creates all databases and service users

-- Auth
CREATE DATABASE auth;
CREATE USER auth_user WITH PASSWORD 'CHANGE_ME_AUTH';
GRANT ALL PRIVILEGES ON DATABASE auth TO auth_user;

-- Mail
CREATE DATABASE mail;
CREATE USER mail_user WITH PASSWORD 'CHANGE_ME_MAIL';
GRANT ALL PRIVILEGES ON DATABASE mail TO mail_user;

-- Chat
CREATE DATABASE chat;
CREATE USER chat_user WITH PASSWORD 'CHANGE_ME_CHAT';
GRANT ALL PRIVILEGES ON DATABASE chat TO chat_user;

-- BYND
CREATE DATABASE bynd;
CREATE USER bynd_user WITH PASSWORD 'CHANGE_ME_BYND';
GRANT ALL PRIVILEGES ON DATABASE bynd TO bynd_user;

-- Veritas
CREATE DATABASE veritas;
CREATE USER veritas_user WITH PASSWORD 'CHANGE_ME_VERITAS';
GRANT ALL PRIVILEGES ON DATABASE veritas TO veritas_user;

-- CNTX
CREATE DATABASE cntx;
CREATE USER cntx_user WITH PASSWORD 'CHANGE_ME_CNTX';
GRANT ALL PRIVILEGES ON DATABASE cntx TO cntx_user;

-- VEIL
CREATE DATABASE veil;
CREATE USER veil_user WITH PASSWORD 'CHANGE_ME_VEIL';
GRANT ALL PRIVILEGES ON DATABASE veil TO veil_user;

-- Heal
CREATE DATABASE heal;
CREATE USER heal_user WITH PASSWORD 'CHANGE_ME_HEAL';
GRANT ALL PRIVILEGES ON DATABASE heal TO heal_user;

-- Ascend
CREATE DATABASE ascend;
CREATE USER ascend_user WITH PASSWORD 'CHANGE_ME_ASCEND';
GRANT ALL PRIVILEGES ON DATABASE ascend TO ascend_user;

-- Ziro
CREATE DATABASE ziro;
CREATE USER ziro_user WITH PASSWORD 'CHANGE_ME_ZIRO';
GRANT ALL PRIVILEGES ON DATABASE ziro TO ziro_user;

-- NoxSoft MCP
CREATE DATABASE noxsoft_mcp;
CREATE USER mcp_user WITH PASSWORD 'CHANGE_ME_MCP';
GRANT ALL PRIVILEGES ON DATABASE noxsoft_mcp TO mcp_user;

-- SVRN
CREATE DATABASE svrn;
CREATE USER svrn_user WITH PASSWORD 'CHANGE_ME_SVRN';
GRANT ALL PRIVILEGES ON DATABASE svrn TO svrn_user;
